### ISSUE TITLE
Align event categories so as to remove non-capitalised ones, etc.

### ISSUE THREAD

**Issue by ocorcho** [3cixty/knowledgebase#43]
Currently several event categories are used (those from eventful and those from evensi). The others (pomodoro, teatri, fieradimilano, etc.) are in general well aligned to existing eventful categories. 

These categories should be aligned completely

**Comment by rtroncy** [comment]
@ocorcho Can you indicate the link to the reconciled event categories resources?

**Comment by ocorcho** [comment]
You can evaluate this query (see [here](http://91.250.81.138:8890/sparql?default-graph-uri=&query=select+distinct+%3Fy+where+%7B%3Fx+a+lode%3AEvent+%3B+lode%3AhasCategory+%3Fy%7D+&format=text%2Fhtml&timeout=0&debug=on))
```
SELECT DISTINCT ?y WHERE 
{
  ?x a lode:Event ; 
       lode:hasCategory ?y
}
```

**Comment by rtroncy** [comment]
My bad, event categories are still just strings and I keep thinking that they are URIs, sorry! This issue can be closed. #34 is still open !
