### ISSUE TITLE
EAN Place instances do not have a locationOnt:cell property attached

### ISSUE THREAD

**Issue by giusepperizzo** [3cixty/knowledgebase#48]
Testing on beta:
```
SELECT DISTINCT count(distinct ?venue) WHERE {
	GRAPH <http://3cixty.com/places> {?venue a dul:Place .}
	?venue dc:publisher <http://www.expedia.com>. }
```
produces 524 places while
```
SELECT DISTINCT count(distinct ?venue) WHERE {
	GRAPH <http://3cixty.com/places> {?venue a dul:Place .}
	?venue locationOnt:cell ?cell .
	?venue dc:publisher <http://www.expedia.com>. }
```
gives 0 places.
The only difference is the ```locationOnt:cell``` property. 

Further investigating, if we take the dump https://github.com/3cixty/knowledgebase/blob/master/data/dump/expedia/2015-04-28.zip
we have two files 
- hotelsCells.ttl
- hotels.ttl 

The hotelsCells contains the triples as in the following format: 
place  locationOnt:cell  uri_cell

However, the place links are not available in the hotels.ttl file. There is a mismatch. Probably due to a misalignment in the process of generating the places and adding them the cell identifiers.

@ocorcho @jcballesteros can you please check? Add @Kai-Dominik @AnthonyJameson @rtroncy @jplu for closely following the issue.

**Comment by ocorcho** [comment]
Patch is already applied on beta. See the proposal in #53 to follow a more systematic approach for this.
