### ISSUE TITLE
Evensi Event instances do not have a locationOnt:cell property attached

### ISSUE THREAD

**Issue by giusepperizzo** [3cixty/knowledgebase#49]
This is related to issue #48 . 

Source of the problem: using UUIDs as identifiers for the event instances that change at any run, it breaks legacy dependencies with the patches such as the one that adds the cell identifiers.
  
This triggers to better handle the addition of the cells to all place and event instances we have in the KB. 

Tagging @Kai-Dominik @AnthonyJameson @ocorcho @jcballesteros @rtroncy for closely following.

**Comment by ocorcho** [comment]
Check the proposal that I have made on using SPARQL Update patches for the materialisation of the information on cells for every event and place. See #53

**Comment by ocorcho** [comment]
We have now committed (a31a776590d2cc71d4e31b6c9f5dc68258e626a2) a patch query that will make sure that all places with geocoordinates and no cell assigned can be assigned their corresponding cell in the Milano Grid. 

This patch query is available at https://github.com/3cixty/knowledgebase/blob/master/data/patch/eventCells/eventCells.sparql

**Comment by rtroncy** [comment]
@jplu Can you also please confirm that KBDeploy takes into account this patch query when being launched?

**Comment by jplu** [comment]
Yes.
