### ISSUE TITLE
Make sure that EXPO Events are included in the reconciled dataset

### ISSUE THREAD

**Issue by ocorcho** [3cixty/knowledgebase#54]
For the time being I have evaluated this query
```
CONSTRUCT 
{
?event a lode:Event
}
WHERE
{
	GRAPH <http://3cixty.com/expo> {?event a lode:Event}
} 
```
And have uploaded the result into the GRAPH <http://3cixty.com/events>

**Comment by giusepperizzo** [comment]
6b9b605fe05d93dba7adf59641836ea33e263a25 fixes the issue, adding up 144 events in /events (from 11804 to 11948).

@ocorcho pls check if the file 3cixty-EXPOEvents-ForReconciledEvents in data/dump/expo/2015-05-05.zip is needed.

**Comment by ocorcho** [comment]
It is not needed anymore, of course. So it should be then removed from the dumps now. No harm anyway if they are loaded, but obviously they should not be there for the next steps once the new reconciliation has been made taking into account that data.

**Comment by ocorcho** [comment]
@giusepperizzo Can you please remove them? I cannot do properly the zip generation in my computer.

**Comment by rtroncy** [comment]
Done and closing.
