### ISSUE TITLE
Make sure that cells are generated for all EXPO Events (the ones manually inserted)

### ISSUE THREAD

**Issue by ocorcho** [3cixty/knowledgebase#55]
This has to be done propertly. For the time being, after adding the manually generated EXPO events in the triple store (graph http://3cixty.com/expo, so that they are together with the ones in ExpoInCitta), the following query has been run:
```
CONSTRUCT
{
    ?event locationOnt:cell ?cell .

} 
WHERE {
    GRAPH <http://3cixty.com/expo> {?event a lode:Event .}
    FILTER NOT EXISTS {?event locationOnt:cell ?cell2}.
    ?event lode:inSpace ?geometry .
    ?geometry geo:long ?long .
    ?geometry geo:lat ?lat .
        ?geometry locn:geometry ?geoPlace .
    ?cell a locationOnt:Cell .
        ?cell geo:location ?cellGeo .
    ?cellGeo locn:geometry ?polygon .
        FILTER(bif:st_intersects(?geoPlace,?polygon))
}
```
And the resulting file has been loaded again in the same graph.

**Comment by ocorcho** [comment]
We have now committed (a31a776590d2cc71d4e31b6c9f5dc68258e626a2) a patch query that will make sure that all places with geocoordinates and no cell assigned can be assigned their corresponding cell in the Milano Grid. 

This patch query is available at https://github.com/3cixty/knowledgebase/blob/master/data/patch/placesCells/placesCells.sparql

**Comment by rtroncy** [comment]
@jplu Can you please confirm that KBDeploy takes into account this patch query when being launched?

**Comment by jplu** [comment]
For places and events yes.
