### ISSUE TITLE
Generate correct WKT geometries for bike parks

### ISSUE THREAD

**Issue by ocorcho** [3cixty/knowledgebase#60]
The generation of the WKT literal for bike parks (BikeMi), done with OpenRefine, has the lat long data swapped, and this generates problems when creating the materialisation of cells.

No problems on the user interface side though.

**Comment by jcballesteros** [comment]
Fixed in my latest commit (bc82885069)

I tested in my local enviroment, and after a full kbdeploy this query:

```
	PREFIX locn: <http://www.w3.org/ns/locn#>

	SELECT distinct ?publisher ?thing ?lat ?long ?geo
	WHERE {
	  {{?thing a lode:Event ; lode:inSpace ?geometry}
	   UNION
	   {?thing a dul:Place ; geo:location ?geometry}} .
	  ?thing dc:publisher ?publisher .
	  ?thing rdf:type ?t .
	  ?geometry geo:lat ?lat .
	  ?geometry  geo:long ?long .
	  ?geometry  locn:geometry ?geo .
	  FILTER(((?lat <= 45.567794914783256)&&(?lat >= 45.35668565341486)&&(?long >= 9.011490619692509)&&(?long<=9.312688264185276)))
	  FILTER (NOT EXISTS { ?thing <http://data.linkedevents.org/def/location#cell> ?cell. })
	}
```
Only returns me two results, because the geometry of these points (two bus stops) are out of the grid.

**Comment by rtroncy** [comment]
@jcballesteros Can you provide the URI of those 2 bike parks which are off grid?
This issue is related to #35.

**Comment by jcballesteros** [comment]
There are stops not bike parks. 

http://data.linkedevents.org/transit/Milano/stop/15759
http://data.linkedevents.org/transit/Milano/stop/15760

**Comment by rtroncy** [comment]
Can someone confirm then that the [route 66](http://3cixty.eurecom.fr/sparql?default-graph-uri=&query=select+*%0D%0Awhere+{%0D%0A+%3Fs+%3Fp+%3Chttp%3A%2F%2Fdata.linkedevents.org%2Ftransit%2FMilano%2Froute%2F66%3E%0D%0A}&format=text%2Fhtml&timeout=0&debug=on) and the  [route 902](http://3cixty.eurecom.fr/sparql?default-graph-uri=&query=select+*%0D%0Awhere+{%0D%0A+%3Fs+%3Fp+%3Chttp%3A%2F%2Fdata.linkedevents.org%2Ftransit%2FMilano%2Froute%2F902%3E%0D%0A}&format=text%2Fhtml&timeout=0&debug=on) really get off the grid?

**Comment by ocorcho** [comment]
Tagging @iricelino for this quick check

**Comment by iricelino** [comment]
Yes, line 66 ends up in Peschiera Borromeo (little town south-east of the
city) and line 902 is a suburban one that is fully outside the city of
Milano.
(You can check lines at http://giromilano.atm.it/#/home/cercalinea)

2015-05-11 7:38 GMT+02:00 Oscar Corcho <notifications@github.com>:

> Tagging @iricelino <https://github.com/iricelino> for this quick check
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3cixty/knowledgebase/issues/60#issuecomment-100771424>
> .
>



-- 

http://about.me/iricelino/

    " If you understand what you're doing,
           you're not learning anything. "

**Comment by rtroncy** [comment]
Thanks for checking @iricelino. So what do we do with those two bus lines? Should we:
* just delete them entirely? 
* or cut them when they got off of the grid (this might be complex)? 
* or just let the KB as it is?

**Comment by iricelino** [comment]
my suggestion is to remove entirely line 902 since it is always outside the
city and to leave line 66 as it is since it is mostly within the city.
however, i'm not fully aware of the consequences of letting some bus stops
outside the city in the kb, so you are better judges in this case.

2015-05-11 13:14 GMT+02:00 Raphael Troncy <notifications@github.com>:

> Thanks for checking @iricelino <https://github.com/iricelino>. So what do
> we do with those two bus lines? Should we:
>
>    - just delete them entirely?
>    - or cut them when they got off of the grid (this might be complex)?
>    - or just let the KB as it is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3cixty/knowledgebase/issues/60#issuecomment-100871935>
> .
>



-- 

http://about.me/iricelino/

    " If you understand what you're doing,
           you're not learning anything. "

**Comment by rtroncy** [comment]
@ocorcho @jcballesteros What do you think? Is it just a question of altering the [dcm dump](https://github.com/3cixty/knowledgebase/blob/master/data/dump/dcm/2015-05-06.zip)?

The bus line 902 is identified with <http://data.linkedevents.org/transit/Milano/busLine/32f5132e-9215-4e3b-8106-3afe047ef3ab>, the route is <http://data.linkedevents.org/transit/Milano/route/902>, the route service is <http://data.linkedevents.org/transit/Milano/service/6291> while the geometry is described at <http://data.linkedevents.org/transit/Milano/busLine/32f5132e-9215-4e3b-8106-3afe047ef3ab/geometry>.

Is the ```busStops-csv.ttl``` file also impacted?

**Comment by ocorcho** [comment]
Our preference would be to leave them. As they have no cell assigned they will not be shown on the user interfaces anyway, so we should not worry about them.
Can we close this issue then?

**Comment by rtroncy** [comment]
I agree with @ocorcho
